### ISSUE TITLE
Error swallowing in `runModule`

### ISSUE THREAD

**Issue by andreasabel** [martijnbastiaan/doctest-parallel#28]
This catch-all case swallows error messages:
https://github.com/martijnbastiaan/doctest-parallel/blob/03bd28cd91eb98e3baa63a2faef45efb317c650a/src/Test/DocTest/Internal/Runner.hs#L251-L252

This is _the_ (only) place where `UpdateImportError` is thrown, AFAICT, which gives the following error message to the user:
```
Could not import module: <FOO>. This can be caused by a number of issues: 

 1. A module found by GHC contained tests, but was not in 'exposed-modules'.

 2. For Cabal users: Cabal did not generate a GHC environment file. Either:
   * Run with '--write-ghc-environment-files=always'
   * Add 'write-ghc-environment-files: always' to your cabal.project

 3. For Cabal users: Cabal did not generate a GHC environment file in time. This
    can happen if you use 'cabal test' instead of 'cabal run doctests'. See
    https://github.com/martijnbastiaan/doctest-parallel/issues/22.

 4. The testsuite executable does not have a dependency on your project library. Please
    add it to the 'build-depends' section of the testsuite executable.
```
I checked all the four points in my case, but I still see this error.
So, there might be more reasons why my doctests do not run.
But it is very hard to make progress if possible hints are not communicated to the user.

**Comment by martijnbastiaan** [comment]
Good point. `UpdateImportError` should be extended such that it carries the actual error message. Then, these locations should be updated:

https://github.com/martijnbastiaan/doctest-parallel/blob/03bd28cd91eb98e3baa63a2faef45efb317c650a/src/Test/DocTest/Internal/Runner.hs#L125

https://github.com/martijnbastiaan/doctest-parallel/blob/03bd28cd91eb98e3baa63a2faef45efb317c650a/src/Test/DocTest/Internal/Runner.hs#L332-L352

**Comment by martijnbastiaan** [comment]
@andreasabel Does this help you: https://github.com/martijnbastiaan/doctest-parallel/pull/29?

**Comment by andreasabel** [comment]
Let me try this, but tomorrow.  My current state is here: https://github.com/haskell/hackage-server/pull/1014/files

**Comment by martijnbastiaan** [comment]
I think we should create a temporary directory in here:

https://github.com/martijnbastiaan/doctest-parallel/blob/03bd28cd91eb98e3baa63a2faef45efb317c650a/ghci-wrapper/src/Language/Haskell/GhciWrapper.hs#L54-L56

Store it here:

https://github.com/martijnbastiaan/doctest-parallel/blob/03bd28cd91eb98e3baa63a2faef45efb317c650a/ghci-wrapper/src/Language/Haskell/GhciWrapper.hs#L48-L52

And finally clean it up here:

https://github.com/martijnbastiaan/doctest-parallel/blob/03bd28cd91eb98e3baa63a2faef45efb317c650a/ghci-wrapper/src/Language/Haskell/GhciWrapper.hs#L89-L91

I'll have a look at it later (and I'm also happy to accept PRs of course).

**Comment by martijnbastiaan** [comment]
Actually, that wouldn't really work, as we critically depend on the presence of the GHC environment files. Hmm. Not entirely sure what to do.

**Comment by andreasabel** [comment]
Would it help if the modules were not in the root of the repo, but in a subdirectory like `src/`?  This seems to be recommended anyway, `hackage-server` is an outlier here for historic reasons.  For my experiment with `doctest` (https://github.com/haskell/hackage-server/pull/1013) I had to do the same, move the code to `src/`.

**Comment by martijnbastiaan** [comment]
Yes, that would resolve that issue.

**Comment by andreasabel** [comment]
Ok, you won me over to `doctest-parallel`: https://github.com/haskell/hackage-server/pull/1014

**Comment by martijnbastiaan** [comment]
Yay! I see you're saying that `doctest-parallel` isn't much faster: this is probably due to a single module taking the whole length of the run. In my experience this is due to large `$setup` blocks, which are run over and over again. If it really annoys you it might be worth investigating.

I do still think this is an issue with `doctest-parallel` though, it should be able to run tests within modules in parallel too. This will take a bit more engineering though, and I was already reasonably satisfied with the speedups I got..

**Comment by andreasabel** [comment]
> Yay! I see you're saying that `doctest-parallel` isn't much faster: this is probably due to a single module taking the whole length of the run.

Indeed, only a single module out of 200 has doctests, and only 2, so there cannot be much speedup by parallel execution.  It might pay off more once there are more doctests.

The setup block is small (I suppose):
```
-- $setup
-- >>> :set -XOverloadedStrings
-- >>> import Data.ByteString.Lazy.Char8 ()
```

**Comment by martijnbastiaan** [comment]
Ah right. Yeah your runtime is going to be dominated by parsing all the modules..

**Comment by andreasabel** [comment]
I wonder whether it would be sensible to cache the doctest-extraction step.  If the modules are handled independently, then one could store the hash of the module source, and with it the extracted doctests.  If the hash is still the same, the module would not have to be parsed again.  Computing a hash is cheap.

**Comment by martijnbastiaan** [comment]
I've just ran doctest-parallel on `hackage-server` - while test time does seem to be dominated by parsing it only takes a few seconds:

```
$ cabal build DocTests
$ time cabal run DocTests
Up to date
Examples: 3  Tried: 3  Errors: 0  Unexpected output: 0

real	0m3,932s
user	0m3,719s
sys	0m0,224s
```

While it would be nice to shave off those couple of seconds, I doubt it's worth the effort. I'm also hoping we'll get docstrings in `.hi` files soon, which would make discovering the tests a matter of milliseconds :smile:
