### ISSUE TITLE
Dealing with extra C includes

### ISSUE THREAD

**Issue by lehins** [martijnbastiaan/doctest-parallel#7]
What is the correct way to deal with any C files that are included with a project. Currently I am trying to switch `vector` to use `doctest-parallel`. For `doctest` setup was:

```haskell
import Test.DocTest (doctest)

main :: IO ()
main = doctest ["-Iinclude", "-Iinternal", "src/Data"]
```

but for `doctest-parallel` suggested setup:

```haskell
main :: IO ()
main = mainFromCabal "vector" =<< getArgs
```

doesn't work and yields errors along the lines:

```
/home/lehins/haskell/vector/vector/src/Data/Vector/Fusion/Bundle/Monadic.hs:117:2: error:
     fatal error: vector.h: No such file or directory
      117 | #include "MachDeps.h"
          |  ^~~~~~~~~~
    |
117 | #include "MachDeps.h"
    |  ^
compilation terminated.

/home/lehins/haskell/vector/vector/src/Data/Vector/Fusion/Bundle.hs:109:2: error:
     fatal error: vector.h: No such file or directory
      109 | 
          |  ^         
    |
109 | 
    |  ^
compilation terminated.
```

Any suggestions? If it is possible to make it work then it would be great to add an example to README. It is not uncommon for users to have cbits for performance critical parts.

**Comment by martijnbastiaan** [comment]
Could you try the patch in https://github.com/martijnbastiaan/doctest-parallel/pull/8? It should pass the necessary `-I` flags to GHC while parsing. I have yet to find a suitable regression test, the current one succeeds even without the patch applied even though it seems to mimic the `vector` case..

**Comment by martijnbastiaan** [comment]
As for the long term: Haddock comments should soon (GHC 9.4?) be included in compiled files, which would eliminate the need for `doctest-paralell` to call GHC to parse sources files at all. This would sidestep all the issues related to flags and compile directives.

**Comment by martijnbastiaan** [comment]
@lehins I've release `0.2.1` which includes the C-include fix.
