### ISSUE TITLE
need explicit LANGUAGE pragma while running Haskell2010

### ISSUE THREAD

**Issue by GrootProgrammer** [martijnbastiaan/doctest-parallel#85]
Following the example written at [Examples/](https://github.com/martijnbastiaan/doctest-parallel/blob/main/example/README.md) and then creating code using a Haskell2010 feature generates an error on running doctests without explicit language extension

e.g.

```hs
module MyLib (someFunc) where

data (Show a) => ShowProxy a = Prox a
  deriving (Show)

showViaProxy :: (Show a) => a -> IO ()
showViaProxy a = putStrLn $ show $ Prox a

someFunc :: IO ()
someFunc = showViaProxy "hello world!"
```
gives:
```
$ cabal build
```
successful, but:
```
$ cabal run doctests
/home/user/doctest-issue/src/MyLib.hs:3:6: error: [GHC-87429]
    Illegal datatype context: (Show a) =>
    Suggested fix: Perhaps you intended to use DatatypeContexts
  |
3 | data (Show a) => ShowProxy a = Prox a
  |      ^^^^^^^^
```

manually enabling the language version in the .hs file as such makes the code testable:
```hs
{-# LANGUAGE Haskell2010 #-}

module MyLib (someFunc) where

data (Show a) => ShowProxy a = Prox a
  deriving (Show)

showViaProxy :: (Show a) => a -> IO ()
showViaProxy a = putStrLn $ show $ Prox a

someFunc :: IO ()
someFunc = showViaProxy "hello world!"
```
```
$ cabal run doctests
[INFO   ] [ThreadId 4] Examples: 0  Tried: 0  Errors: 0  Unexpected output: 0
```

**Comment by martijnbastiaan** [comment]
Makes sense. We should take into account language extensions enabled by default over here:

https://github.com/martijnbastiaan/doctest-parallel/blob/fc101335deda64749af5d24e9740be831a127720/src/Test/DocTest/Helpers.hs#L91

Amazing that we haven't caught this before!

**Comment by martijnbastiaan** [comment]
I've provided a fix in:

https://github.com/martijnbastiaan/doctest-parallel/pull/86

In the mean time, you can call your `doctest-parallel` binary with `--ghc-arg=-XHaskell2010`, or add it to `doctests.hs` like this:

```haskell
main :: IO ()
main = do
  args <- getArgs
  mainFromCabal "your-project" ("--ghc-arg=-XHaskell2010":args)
```
