### ISSUE TITLE
Testing with GHC 9.2 complains about environment files

### ISSUE THREAD

**Issue by lehins** [martijnbastiaan/doctest-parallel#9]
For some reason when building with ghc-9.2 I run into a problem. Same error message pops up when building without `--write-ghc-environment-files=always` flag on ghc-8.10.4 However, adding the flag for ghc-9.2 doesn't fix the problem unfortunately

```shell
$ cabal test vector:vector-doctest --write-ghc-environment-files=always
...
See the example project at https://github.com/martijnbastiaan/doctest-parallel/tree/master/examples for more information.
Could not import module: Data.Vector.Primitive. This can be caused by a number of issues: 

 1. A module found by GHC contained tests, but was not in 'exposed-modules'.

 2. For Cabal users: Cabal did not generate a GHC environment file. Either:
   * Run with '--write-ghc-environment-files=always'
   * Add 'write-ghc-environment-files: always' to your cabal.project

 3. The testsuite executable does not have a dependency on your project library. Please add it to the 'build-depends' section of the testsuite executable.

See the example project at https://github.com/martijnbastiaan/doctest-parallel/tree/master/examples for more information.
Examples: 501  Tried: 0  Errors: 6  Unexpected output: 0
*** Exception: <stdout>: hPutChar: resource vanished (Broken pipe)
```

Here is a branch that will reproduce this behavior: https://github.com/haskell/vector/tree/doctest-parallel

**Comment by lehins** [comment]
Cabal is damn mystery to me. Adding the `write-ghc-environment-files: always` flag to `project.cabal` solved the problem, but passing over cli didn't :man_shrugging:

**Comment by lehins** [comment]
There is some minor problem with doctest-parallel though. See the error on the bottom:
```
*** Exception: <stdout>: hPutChar: resource vanished (Broken pipe)
```

That ideally should not be there. I don't think it is critical, though.

**Comment by martijnbastiaan** [comment]
I wonder if running it with `cabal run vector:vector-doctest` (`test` => `run`) would work. But yeah, environment files (at least their current implementation) suck.
